Various fixes

diff --git a/links/bin/build/install b/links/bin/build/install
--- a/links/bin/build/install
+++ b/links/bin/build/install
@@ -9,15 +9,27 @@ function checkp() {
 
 function doWork() {
     local RED='\033[0;31m'
-    local GREEN='\033[0;32m'
     local RESET='\033[0m'
+
+    local settings="${1}"
+    if [ -z "${settings}" ]; then
+        printf "${RED}Settings file is not provided${RESET}\n"
+        exit 1
+    fi
+    # shellcheck disable=SC1090
+    if ! source "$(dirname "${0}")/${settings}"; then
+        printf "${RED}Settings path does not exist${RESET}\n"
+        exit 1
+    fi
+
+    local GREEN='\033[0;32m'
 
     local OS_ID arr
     printf "${GREEN}Checking OS${RESET}\n"
     OS_ID=$(sed -ne 's/^ID=\(.*\)/\1/p' /etc/os-release)
     case "${OS_ID}" in
-        arch) arr=() ;;
-        ubuntu) arr=(libncursesw5-dev libmagic-dev) ;;
+        arch) arr=( "${_INST_ARCH_ARR[@]}" ) ;;
+        ubuntu) arr=( "${_INST_UB_ARR[@]}" ) ;;
         *)
             printf "${RED}Unsupported OS: ${OS_ID}${RESET}\n"
             exit 1
@@ -26,61 +38,67 @@ function doWork() {
     local pnames=""
     printf "${GREEN}Checking prerequisites packages to install:${RESET}\n\n"
     for i in "${arr[@]}"; do
-        checkp "${i}" && printf "${GREEN}*${RESET} $i ${GREEN}is installed${RESET}\n" || pnames="${pnames} $i"
+        checkp "${OS_ID}" "${i}" && printf "${GREEN}*${RESET} $i ${GREEN}is installed${RESET}\n" || pnames="${pnames} $i"
     done
     if [ -n "${pnames}" ]; then
         printf "${RED}Installing the following packages:${RESET}\n${pnames}\n"
         case "${OS_ID}" in
-            arch) yes | sudo /usr/bin/pacman -Sy ${pnames} ;;
+            arch) sudo /usr/bin/pacman -Sy --noconfirm ${pnames} ;;
             ubuntu) sudo /usr/bin/apt-get update && sudo /usr/bin/apt-get install -y ${pnames} ;;
         esac
     else
         printf "${GREEN}All packages are installed${RESET}\n"
     fi
 
-    local dir=~/github/vifm
-    if [ -d "${dir}" ]; then
-        pushd "${dir}" > /dev/null || exit 1
+    printf "${GREEN}Updating Git code${RESET}\n"
+    if [ -d "${_INST_SRC_DIR}" ]; then
+        pushd "${_INST_SRC_DIR}" > /dev/null || exit 1
         git reset --hard
-        if ! git pull origin master; then
-            printf "${RED}Make failed${RESET}\n"
+        if ! git pull origin ${_INST_SRC_BRANCH}; then
+            printf "${RED}Git pull failed${RESET}\n"
+            popd > /dev/null || exit 1
+            exit 1
+        fi
+        if ! git submodule update --init; then
+            printf "${RED}Git submodule update failed${RESET}\n"
             popd > /dev/null || exit 1
             exit 1
         fi
     else
-        mkdir -p "${dir}"
-        if ! git clone https://github.com/vifm/vifm.git "${dir}"; then
+        mkdir -p "${_INST_SRC_DIR}"
+        if ! git clone --recursive "${_INST_SRC_URL}" "${_INST_SRC_DIR}"; then
             printf "${RED}Git clone failed${RESET}\n"
             popd > /dev/null || exit 1
             exit 1
         fi
-        pushd "${dir}" > /dev/null || exit 1
+        pushd "${_INST_SRC_DIR}" > /dev/null || exit 1
     fi
 
+    printf "${GREEN}Starting configure${RESET}\n"
     CFLAGS+=' -fcommon'
-    if ! ./configure; then
+    [ ! -f ./configure ] && autoreconf -i
+    if ! ./configure ${_INST_SRC_CONF_PARAMS}; then
         printf "${RED}Configure failed${RESET}\n"
         popd > /dev/null || exit 1
         exit 1
     fi
+    printf "${GREEN}Starting make${RESET}\n"
     if ! make; then
         printf "${RED}Make failed${RESET}\n"
         popd > /dev/null || exit 1
         exit 1
     fi
 
-    local inst_dir=~/.zsh/volatile/igorepst/_gh_release/vifm/vifm
+    local inst_dir=~/.zsh/volatile/igorepst/_gh_release/${_INST_DEST_DIR}
     local bin_dir=~/.zsh/volatile/igorepst/_gh_release/_cache/_bin
     local compl_dir=~/.zsh/volatile/igorepst/_gh_release/_cache/_compl
     mkdir -p "${inst_dir}"
-    cp -r data src/vifm src/vifm-pause data/shell-completion/zsh/_vifm "${inst_dir}"
-    ln -sf "${inst_dir}/vifm" "${bin_dir}/vifm"
-    ln -sf "${inst_dir}/vifm-pause" "${bin_dir}/vifm-pause"
-    ln -sf "${inst_dir}/_vifm" "${compl_dir}/_vifm"
+    _inst "${inst_dir}" "${bin_dir}" "${compl_dir}"
     rm -f ~/.zsh/volatile/zcompdump* 2> /dev/null
 
     popd > /dev/null || exit 1
+    printf "${GREEN}Done successfully${RESET}\n"
     exec zsh
 }
 
-doWork
+doWork "$@"
